//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyUrl.API.Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinyUrl.API.Recources.ResponseMessages", typeof(ResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path should be between 8 and 16 characters.
        /// </summary>
        internal static string PathIsTooShort {
            get {
                return ResourceManager.GetString("PathIsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ahphanumeric subsequences such as &apos;abc&apos;, &apos;321&apos; etc..
        /// </summary>
        internal static string PathNoAlphaNumbericSubsequences {
            get {
                return ResourceManager.GetString("PathNoAlphaNumbericSubsequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path should have at least one digit.
        /// </summary>
        internal static string PathNoDigits {
            get {
                return ResourceManager.GetString("PathNoDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path should have at least one letter.
        /// </summary>
        internal static string PathNoLetters {
            get {
                return ResourceManager.GetString("PathNoLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny Url with this path already exists.
        /// </summary>
        internal static string UrlDuplicated {
            get {
                return ResourceManager.GetString("UrlDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny Url does not exist.
        /// </summary>
        internal static string UrlNotExist {
            get {
                return ResourceManager.GetString("UrlNotExist", resourceCulture);
            }
        }
    }
}
